# Site settings
title: OliDaily
description: Oliver Deng
favicon: /assets/img/oliver-github.png
baseurl:
url: https://dsy401.github.io
rss_url:

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page/:num"
<<<<<<< HEAD

=======
>>>>>>> f1195dcc63ccb60ac9efd7a3c1d1777e1c924014
highlight: true
#highlighter: rouge

#timezone: Antarctica/McMurdo
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
